name: Bug Report
description: File a bug report here
title: "BUG: "
labels: ["bug"]
assignees: ["eslutz"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.  Please make sure there aren't any open/closed issues for this topic.

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give a brief description of the issue and what was expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: potential-fix
    attributes:
      label: Potential fix for the bug
      description: Give a brief description of potential fix.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information or context such as logs, screenshots, or scenarios in which the bug occurs to facilitate resolving the issue.
    validations:
      required: false
